### ISSUE TITLE
Serial breaks the code

### ISSUE THREAD

**Issue by Persojet** [Stiju/arduino_snake#3]
Enabling serial (for statistics) breaks the code, and screen stays empty.

**Comment by Stiju** [comment]
That’s because there’s not enough memory on the Arduino. You can free up memory by decreasing the snakes max length. Set kMaxLength to a lower value and it should work.

**Comment by Persojet** [comment]
Seems to resolve issue. Didn't realize space was so limited when over half was available for local variables.
